<?php

/**
 * Implements hook_views_api().
 */
function commerce_add_to_cart_extras_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_form_alter().
 *
 * If this is a Views Form (determined by $form_id) that contains this module's
 * quantity handler, alter the label of the submit button to "Add to cart".
 */
function commerce_add_to_cart_extras_form_alter(&$form, &$form_state, $form_id) {
  $is_quantity_form = FALSE;
  if (strpos($form_id, 'views_form_') === 0) {
    $view = $form_state['build_info']['args'][0];
    foreach ($view->field as $field) {
      if ($field instanceof commerce_add_to_cart_extras_handler_field_quantity) {
        $is_quantity_form = TRUE;
      }
    }
  }

  if ($is_quantity_form) {
    $form['actions']['submit']['#value'] = t('Add to cart');
  }
}
