; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.8"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[commerce_kickstart][download][type] = ""
projects[commerce_kickstart][download][url] = ""
projects[commerce_kickstart][type] = "module"
projects[commerce_kickstart][subdir] = "profiles/commerce_kickstart"
projects[commerce_kickstart][version] = "1.x-dev"

projects[views_bulk_operations][version] = "3.0-beta3"

projects[addressfield][subdir] = "profiles/commerce_kickstart/modules/addressfield"
projects[addressfield][version] = "1.0-beta2"

projects[ctools][subdir] = "profiles/commerce_kickstart/modules/ctools"
projects[ctools][version] = "1.0-rc1"

projects[cloud_zoom][version] = "1.0"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Modules
projects[commerce][subdir] = "profiles/commerce_kickstart/modules/commerce"
projects[commerce][version] = "1.0"

projects[commerce_addressbook][version] = "1.x-dev"

projects[commerce_checkout_login][version] = "1.x-dev"

projects[commerce_features][version] = "1.x-dev"

projects[commerce_shipping][version] = "2.x-dev"

projects[commerce_stock][version] = "1.x-dev"

projects[commerce_vbo_views][version] = "1.0-alpha1"

projects[commerce_wishlist][version] = "1.x-dev"

projects[cool_message][version] = "1.0-beta1"

projects[dbtng_migrator][version] = "1.0"

projects[delta][version] = "3.0-beta8"

projects[double_field][version] = "1.0-rc1"

projects[entity][version] = "1.x-dev"

projects[features_extra][version] = "1.x-dev"

projects[features][version] = "1.0-beta4"

projects[fivestar][version] = "2.0-alpha1"

projects[hierarchical_select][version] = "3.0-alpha5"

projects[imagecache_actions][version] = "1.x-dev"

projects[libraries][version] = "1.0"

projects[logintoboggan][version] = "1.2"

projects[manual-crop][version] = "1.2"

projects[pathauto][version] = "1.0-rc2"

projects[physical][version] = "1.x-dev"

projects[rules][version] = "2.0"

projects[sweaver][version] = "1.x-dev"

projects[taxonomy_block][version] = "1.0"

projects[token][version] = "1.0-beta6"

projects[transliteration][version] = "3.0"

projects[views][subdir] = "profiles/commerce_kickstart/modules/views"
projects[views][version] = "3.0-rc1"

projects[views_php][version] = "1.x-dev"

projects[views_slideshow][version] = "3.x-dev"

projects[votingapi][version] = "2.x-dev"

; Themes
projects[omega][subdir] = "sites/all/themes"
projects[omega][version] = "3.0"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

