<?php

/**
 * @file
 * Provides the wishlist for use in Drupal Commerce.
 */

/**
 * Implements hook_menu().
 */
function commerce_wishlist_menu() {
  $items = array();

  $items['user/%user/wishlist/delete/%'] = array(
    'page callback' => 'commerce_wishlist_delete',
    'page arguments' => array(1, 4),
    'access callback' => 'commerce_wishlist_access',
    'access arguments' => array(1, 4),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function commerce_wishlist_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_wishlist') . '/includes/views',
  );
}

/**
 * Implements hook_permission().
 */
function commerce_wishlist_permission() {
  return array(
    'view own wishlist' => array(
      'title' => t('View own wishlist'),
      'description' => t('Allows a user to see their own wishlist.'),
    ),
    'administer wishlists' => array(
      'title' => t('Administer wishlist'),
      'description' => t('Allows users to perform any action on wishlists. <em>Warning: Give to trusted roles only; this permission has security implications.</em>'),
    ),
  );
}

/**
 * Implements hook_commerce_cart_product_add().
 */
function commerce_wishlist_commerce_cart_product_add($order, $product, $quantity, $line_item) {
  // When add product to cart delete product from wishlist
  db_delete('commerce_wishlist')
    ->condition(db_and()
      ->condition('uid', $order->uid)
      ->condition('product_id', $product->product_id)
    )
    ->execute();
}

/**
 * Determine whether the user has a given privilege to wishlist.
 */
function commerce_wishlist_access($user, $wishlist_id = '') {
  if (user_access('administer wishlist')) return TRUE;

  if (isset($wishlist_id)) {
    $result = db_select('commerce_wishlist', 'cw')
      ->addTag('wishlist')
      ->fields('cw', array('uid'))
      ->condition('wishlist_id', $wishlist_id)
      ->execute()
      ->fetchAssoc();
  }

  if ($result['uid'] == $user->uid && user_access('view own wishlist')) return TRUE;

  return FALSE;
}

/**
 * Implements hook_form_alter().
 */
function commerce_wishlist_form_alter(&$form, &$form_state, $form_id) {
  if (strstr($form_id, 'commerce_cart_add_to_cart_form')) {
    if (isset($form_state['build_info']['args'][0]->data['context']['view'])) {
      if ($form_state['build_info']['args'][0]->data['context']['view']['view_name'] == 'wishlist') {
        return;
      }
    }

    $form += commerce_wishlist_add_form();
    $form['#submit'] = array('commerce_wishlist_add_form_submit');
    $form['#validate'][] = 'commerce_wishlist_add_form_validate';
  }
}

/**
 * Form callback for add a new button of commerce_cart_add_to_cart_form()
 */
function commerce_wishlist_add_form() {
  $form['add_to_wishlist'] = array(
    '#type' => 'submit',
    '#value' => t('Add to Wishlist'),
    '#attributes' => array('class' => array('wishlist')),
  );

  return $form;
}

/**
 * Validate callback for commerce_cart_add_to_cart_form().
 */
function commerce_wishlist_add_form_validate($form, &$form_state) {
  global $user;
  if ($form_state['values']['op'] == t('Add to Wishlist')) {
    // Verify if is a registed user_access
    if (!$user->uid) {
      form_set_error('add_to_wishlist',
        t('<a href="@login">Log in</a> or <a href="@register">register</a> to add this product to your wishlist.',
          array('@login' => url('user/login', array('query' => drupal_get_destination())), '@register' => url('user/register'))
        )
      );
    }

    // Verify if this prodcut has been added to wishlist
    $conditions = db_and();
    $conditions->condition('uid', $user->uid);
    $conditions->condition('product_id', $form_state['values']['product_id']);
    
    if (isset($form_state['build_info']['args'][2]['entity'])) {
      $conditions->condition('nid', $form_state['build_info']['args'][2]['entity']->nid);
    }
    
    $result = db_select('commerce_wishlist', 'cw')
      ->addTag('wishlist')
      ->fields('cw', array('wishlist_id'))
      ->condition($conditions)
      ->execute()
      ->fetchAssoc();

    if (isset($result['wishlist_id'])) {
      form_set_error('add_to_wishlist', t('This product is already in your wishlist.'));
    }
  }
}

/**
 * Submit callback for commerce_cart_add_to_cart_form().
 *
 * Override of commerce_cart_add_to_cart_form_sumbit to add wishlist adicional function
 */
function commerce_wishlist_add_form_submit($form, &$form_state) {
  global $user;

  if ($form_state['values']['op'] == t('Add to Wishlist')) {
    $fields = array('uid' => $user->uid, 'product_id' => $form_state['values']['product_id'], 'quantity' => $form_state['values']['quantity']);
    if (isset($form_state['build_info']['args'][2]['entity']->nid)) {
      $fields['nid'] = $form_state['build_info']['args'][2]['entity']->nid;
    }
  
    db_insert('commerce_wishlist')
      ->fields($fields)
      ->execute();

    $title = (isset($form_state['build_info']['args'][2]['entity']->title)) ? $form_state['build_info']['args'][2]['entity']->title : $form_state['build_info']['args'][0]->line_item_label;

    drupal_set_message(t('%title added to <a href="!url">your wishlist</a>.', array('%title' => $title, '!url' => url('user/'. $user->uid .'/wishlist'))));
  } else {
    commerce_cart_add_to_cart_form_submit($form, $form_state);
  }
}

/**
 * Access callback: Delete the wishlist product
 */
function commerce_wishlist_delete($user, $wishlist_id) {
  db_delete('commerce_wishlist')
    ->condition('wishlist_id', $wishlist_id)
    ->execute();

  drupal_set_message(t('The product has been deleted from your wishlist.'));
  drupal_goto('user/'. $user->uid .'/wishlist');
}

